---
- name: add-user-test
  hosts: all
  vars:
    - new_userid: awxtest
  tasks:
  - name: check exist users
    shell: cat /etc/passwd | grep {{ new_userid }} || echo "NULL"
    register: rval
 
  - name: adduser
    shell: /usr/sbin/useradd {{ new_userid }}
    when: rval.stdout =='NULL'
